server:
  port: 8081
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          secret: "1ca67cbccbbcba715a9dd252fc221741ef808143ba94d7b01d717b0389bd4ea4f680250033cfd457d1d0a1c9a79046bde8771a1d24345a3b63695787b466be2d"
  application:
    name: "crediya-reportes"
  devtools:
    add-properties: false
  profiles:
    active: local
adapter:
  sqs:
    region: "us-east-2"
    queue-contador-solicitudes-response: "contadorSolicitudesSQS"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
aws:
  dynamodb:
    endpoint: "https://dynamodb.us-east-2.amazonaws.com"
    table-name: "Reportes"
